require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GarbagesController do

  # This should return the minimal set of attributes required to create a valid
  # Garbage. As you add validations to Garbage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "total" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GarbagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all garbages as @garbages" do
      garbage = Garbage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:garbages).should eq([garbage])
    end
  end

  describe "GET show" do
    it "assigns the requested garbage as @garbage" do
      garbage = Garbage.create! valid_attributes
      get :show, {:id => garbage.to_param}, valid_session
      assigns(:garbage).should eq(garbage)
    end
  end

  describe "GET new" do
    it "assigns a new garbage as @garbage" do
      get :new, {}, valid_session
      assigns(:garbage).should be_a_new(Garbage)
    end
  end

  describe "GET edit" do
    it "assigns the requested garbage as @garbage" do
      garbage = Garbage.create! valid_attributes
      get :edit, {:id => garbage.to_param}, valid_session
      assigns(:garbage).should eq(garbage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Garbage" do
        expect {
          post :create, {:garbage => valid_attributes}, valid_session
        }.to change(Garbage, :count).by(1)
      end

      it "assigns a newly created garbage as @garbage" do
        post :create, {:garbage => valid_attributes}, valid_session
        assigns(:garbage).should be_a(Garbage)
        assigns(:garbage).should be_persisted
      end

      it "redirects to the created garbage" do
        post :create, {:garbage => valid_attributes}, valid_session
        response.should redirect_to(Garbage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved garbage as @garbage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Garbage.any_instance.stub(:save).and_return(false)
        post :create, {:garbage => { "total" => "invalid value" }}, valid_session
        assigns(:garbage).should be_a_new(Garbage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Garbage.any_instance.stub(:save).and_return(false)
        post :create, {:garbage => { "total" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested garbage" do
        garbage = Garbage.create! valid_attributes
        # Assuming there are no other garbages in the database, this
        # specifies that the Garbage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Garbage.any_instance.should_receive(:update_attributes).with({ "total" => "MyString" })
        put :update, {:id => garbage.to_param, :garbage => { "total" => "MyString" }}, valid_session
      end

      it "assigns the requested garbage as @garbage" do
        garbage = Garbage.create! valid_attributes
        put :update, {:id => garbage.to_param, :garbage => valid_attributes}, valid_session
        assigns(:garbage).should eq(garbage)
      end

      it "redirects to the garbage" do
        garbage = Garbage.create! valid_attributes
        put :update, {:id => garbage.to_param, :garbage => valid_attributes}, valid_session
        response.should redirect_to(garbage)
      end
    end

    describe "with invalid params" do
      it "assigns the garbage as @garbage" do
        garbage = Garbage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Garbage.any_instance.stub(:save).and_return(false)
        put :update, {:id => garbage.to_param, :garbage => { "total" => "invalid value" }}, valid_session
        assigns(:garbage).should eq(garbage)
      end

      it "re-renders the 'edit' template" do
        garbage = Garbage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Garbage.any_instance.stub(:save).and_return(false)
        put :update, {:id => garbage.to_param, :garbage => { "total" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested garbage" do
      garbage = Garbage.create! valid_attributes
      expect {
        delete :destroy, {:id => garbage.to_param}, valid_session
      }.to change(Garbage, :count).by(-1)
    end

    it "redirects to the garbages list" do
      garbage = Garbage.create! valid_attributes
      delete :destroy, {:id => garbage.to_param}, valid_session
      response.should redirect_to(garbages_url)
    end
  end

end
