require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IdhsController do

  # This should return the minimal set of attributes required to create a valid
  # Idh. As you add validations to Idh, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IdhsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all idhs as @idhs" do
      idh = Idh.create! valid_attributes
      get :index, {}, valid_session
      assigns(:idhs).should eq([idh])
    end
  end

  describe "GET show" do
    it "assigns the requested idh as @idh" do
      idh = Idh.create! valid_attributes
      get :show, {:id => idh.to_param}, valid_session
      assigns(:idh).should eq(idh)
    end
  end

  describe "GET new" do
    it "assigns a new idh as @idh" do
      get :new, {}, valid_session
      assigns(:idh).should be_a_new(Idh)
    end
  end

  describe "GET edit" do
    it "assigns the requested idh as @idh" do
      idh = Idh.create! valid_attributes
      get :edit, {:id => idh.to_param}, valid_session
      assigns(:idh).should eq(idh)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Idh" do
        expect {
          post :create, {:idh => valid_attributes}, valid_session
        }.to change(Idh, :count).by(1)
      end

      it "assigns a newly created idh as @idh" do
        post :create, {:idh => valid_attributes}, valid_session
        assigns(:idh).should be_a(Idh)
        assigns(:idh).should be_persisted
      end

      it "redirects to the created idh" do
        post :create, {:idh => valid_attributes}, valid_session
        response.should redirect_to(Idh.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved idh as @idh" do
        # Trigger the behavior that occurs when invalid params are submitted
        Idh.any_instance.stub(:save).and_return(false)
        post :create, {:idh => {  }}, valid_session
        assigns(:idh).should be_a_new(Idh)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Idh.any_instance.stub(:save).and_return(false)
        post :create, {:idh => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested idh" do
        idh = Idh.create! valid_attributes
        # Assuming there are no other idhs in the database, this
        # specifies that the Idh created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Idh.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => idh.to_param, :idh => { "these" => "params" }}, valid_session
      end

      it "assigns the requested idh as @idh" do
        idh = Idh.create! valid_attributes
        put :update, {:id => idh.to_param, :idh => valid_attributes}, valid_session
        assigns(:idh).should eq(idh)
      end

      it "redirects to the idh" do
        idh = Idh.create! valid_attributes
        put :update, {:id => idh.to_param, :idh => valid_attributes}, valid_session
        response.should redirect_to(idh)
      end
    end

    describe "with invalid params" do
      it "assigns the idh as @idh" do
        idh = Idh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Idh.any_instance.stub(:save).and_return(false)
        put :update, {:id => idh.to_param, :idh => {  }}, valid_session
        assigns(:idh).should eq(idh)
      end

      it "re-renders the 'edit' template" do
        idh = Idh.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Idh.any_instance.stub(:save).and_return(false)
        put :update, {:id => idh.to_param, :idh => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested idh" do
      idh = Idh.create! valid_attributes
      expect {
        delete :destroy, {:id => idh.to_param}, valid_session
      }.to change(Idh, :count).by(-1)
    end

    it "redirects to the idhs list" do
      idh = Idh.create! valid_attributes
      delete :destroy, {:id => idh.to_param}, valid_session
      response.should redirect_to(idhs_url)
    end
  end

end
